name: gamepulse
description: "A modern game info Flutter app with 3D carousel and smooth animations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  url_launcher: ^6.2.2
  # HTTP requests
  http: ^1.5.0

  # Shared Preferences для сохранения сессии
  shared_preferences: ^2.2.2

  # YouTube player
  youtube_player_flutter: ^9.0.3

  # UI Components
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true